// Popular airports for autocomplete — { label, value (IATA code), city }
const AIRPORTS = [
    // India
    { value: 'DEL', label: 'Delhi (DEL)', city: 'Delhi' },
    { value: 'BOM', label: 'Mumbai (BOM)', city: 'Mumbai' },
    { value: 'BLR', label: 'Bangalore (BLR)', city: 'Bangalore' },
    { value: 'HYD', label: 'Hyderabad (HYD)', city: 'Hyderabad' },
    { value: 'MAA', label: 'Chennai (MAA)', city: 'Chennai' },
    { value: 'CCU', label: 'Kolkata (CCU)', city: 'Kolkata' },
    { value: 'AMD', label: 'Ahmedabad (AMD)', city: 'Ahmedabad' },
    { value: 'COK', label: 'Kochi (COK)', city: 'Kochi' },
    { value: 'PNQ', label: 'Pune (PNQ)', city: 'Pune' },
    { value: 'GOI', label: 'Goa (GOI)', city: 'Goa' },
    { value: 'JAI', label: 'Jaipur (JAI)', city: 'Jaipur' },
    { value: 'LKO', label: 'Lucknow (LKO)', city: 'Lucknow' },
    { value: 'IXC', label: 'Chandigarh (IXC)', city: 'Chandigarh' },
    { value: 'PAT', label: 'Patna (PAT)', city: 'Patna' },
    { value: 'BBI', label: 'Bhubaneswar (BBI)', city: 'Bhubaneswar' },
    // International
    { value: 'LHR', label: 'London Heathrow (LHR)', city: 'London' },
    { value: 'LGW', label: 'London Gatwick (LGW)', city: 'London' },
    { value: 'JFK', label: 'New York JFK (JFK)', city: 'New York' },
    { value: 'EWR', label: 'New York Newark (EWR)', city: 'New York' },
    { value: 'LAX', label: 'Los Angeles (LAX)', city: 'Los Angeles' },
    { value: 'ORD', label: 'Chicago O\'Hare (ORD)', city: 'Chicago' },
    { value: 'SFO', label: 'San Francisco (SFO)', city: 'San Francisco' },
    { value: 'DXB', label: 'Dubai (DXB)', city: 'Dubai' },
    { value: 'AUH', label: 'Abu Dhabi (AUH)', city: 'Abu Dhabi' },
    { value: 'DOH', label: 'Doha (DOH)', city: 'Doha' },
    { value: 'SIN', label: 'Singapore (SIN)', city: 'Singapore' },
    { value: 'KUL', label: 'Kuala Lumpur (KUL)', city: 'Kuala Lumpur' },
    { value: 'BKK', label: 'Bangkok (BKK)', city: 'Bangkok' },
    { value: 'HKG', label: 'Hong Kong (HKG)', city: 'Hong Kong' },
    { value: 'NRT', label: 'Tokyo Narita (NRT)', city: 'Tokyo' },
    { value: 'ICN', label: 'Seoul Incheon (ICN)', city: 'Seoul' },
    { value: 'SYD', label: 'Sydney (SYD)', city: 'Sydney' },
    { value: 'MEL', label: 'Melbourne (MEL)', city: 'Melbourne' },
    { value: 'CDG', label: 'Paris Charles de Gaulle (CDG)', city: 'Paris' },
    { value: 'FRA', label: 'Frankfurt (FRA)', city: 'Frankfurt' },
    { value: 'AMS', label: 'Amsterdam (AMS)', city: 'Amsterdam' },
    { value: 'MAD', label: 'Madrid (MAD)', city: 'Madrid' },
    { value: 'BCN', label: 'Barcelona (BCN)', city: 'Barcelona' },
    { value: 'FCO', label: 'Rome Fiumicino (FCO)', city: 'Rome' },
    { value: 'ZRH', label: 'Zurich (ZRH)', city: 'Zurich' },
    { value: 'YYZ', label: 'Toronto (YYZ)', city: 'Toronto' },
    { value: 'MEX', label: 'Mexico City (MEX)', city: 'Mexico City' },
    { value: 'GRU', label: 'São Paulo (GRU)', city: 'São Paulo' },
    { value: 'JNB', label: 'Johannesburg (JNB)', city: 'Johannesburg' },
    { value: 'CAI', label: 'Cairo (CAI)', city: 'Cairo' },
    { value: 'NBO', label: 'Nairobi (NBO)', city: 'Nairobi' },
    { value: 'MNL', label: 'Manila (MNL)', city: 'Manila' },
    { value: 'CGK', label: 'Jakarta (CGK)', city: 'Jakarta' },
    { value: 'IST', label: 'Istanbul (IST)', city: 'Istanbul' },
    { value: 'MOS', label: 'Moscow (SVO)', city: 'Moscow' },
];

export default AIRPORTS;
